### ISSUE TITLE
OPERATOR_YAML_LOCATION

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/anthos-workshop#42]
Ref.
https://github.com/GoogleCloudPlatform/anthos-workshop/blob/771b8d3cb66b2f4c988de0cdb4035926deda3444/env#L37

Is OPERATOR_YAML_LOCATION required? I grepped the files in this repo and don't see any other use of this variable.

I have a whitelisted anthos project and attempting to run the workshop.
I don't have access to gs://anthos-workshop/cfg-op-loc so had to comment this out to proceed.

Anthos Config Management appears to run Ok with this env var commented out.

**Comment by cgrant** [comment]
That variable is no longer used. Thanks for calling it out, we'll clean it up

**Comment by Red-Five** [comment]
This issue was closed but no action was taken on it.

**Comment by cgrant** [comment]
Var removed from env file as part of PR #52
