### ISSUE TITLE
GKE Connect succesfully starts but the cluster is not shown at GCP consoles

### ISSUE THREAD

**Issue by damoresa** [GoogleCloudPlatform/anthos-workshop#47]
Hello!

First of all, I'm not sure of what sort of tagging you're using on this Github, and it is definitely not the best place to ask, but the discussion on [Stackoverflow](https://stackoverflow.com/questions/59319166/gke-connect-succesfully-starts-but-the-cluster-is-not-shown-at-gcp-consoles) seems to be leading nowhere.

I'm writing this issue because after testing out the GKE Connect section of this workshop, the agent seems to be running fine and the gcloud membership command lists my cluster as registered; however, I'm unable to see my cluster on the GCP > Kubernetes Engine clusters list.

All my tests are documented on the [Stackoverflow question](https://stackoverflow.com/questions/59319166/gke-connect-succesfully-starts-but-the-cluster-is-not-shown-at-gcp-consoles), but I'd love if you could tell me what the _whitelisted service account is_ and whether there's any difference between that and a newly created SA with proper permissions (_gkehub.connect_ in this case).

Thanks for your time!

**Edit:** please let me know if you need me to reformat the question into some structured guideline or anything, I've not been able to find anything about question/issue format within the repo.
**Edit 2:** This is the one ["tutorial"](https://github.com/GoogleCloudPlatform/anthos-workshop/blob/master/connect-hub/connect-hub.sh) I've been following.

**Comment by cgrant** [comment]
Anthos by Google Cloud requires a paid subscription in order to use. The
documents you're reviewing work on existing subscriptions. To try or buy
Anthos you'll need to contact sales. The links are on the main Anthos page
here https://cloud.google.com/anthos/

**Comment by damoresa** [comment]
That sort of explains it all.. I figured things bound to APIs would be priced via the API, and heftier stuff like GKE on prem or Migrate for Anthos would actually be billed on another kind of plan.

Thanks for taking the time to answer ;)
Glad I asked before taking more time into guessing what was wrong!
