### ISSUE TITLE
GKE Version Issue

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/anthos-workshop#51]
https://github.com/GoogleCloudPlatform/anthos-workshop/blob/396d97ce72dfee99d0da2779d67241ad1c113c75/env#L15

Version gives Unsupported GKE Version error.

Possibly don't specify version and just use GKE default to avoid this in future?

**Comment by cgrant** [comment]
Version updated in PR #52 
There was an original reason it was included, probably not needed anymore though. Will look to remove it completely in a future PR.

**Comment by miketruty** [comment]
From today: Master version "1.15.7-gke.23" is unsupported.

**Comment by cjcullen** [comment]
I opened https://github.com/GoogleCloudPlatform/anthos-workshop/pull/57 to just specify "1.15" for GKE.

**Comment by cgrant** [comment]
Closing as version was updated to use release version
