### ISSUE TITLE
"Configuring GKE for Multi-Cluster Operation with Istio" Lab won't run due to Helm 3.

### ISSUE THREAD

**Issue by corebug** [GoogleCloudPlatform/anthos-workshop#64]
In [this line](https://github.com/GoogleCloudPlatform/anthos-workshop/blob/771b8d3cb66b2f4c988de0cdb4035926deda3444/hybrid-multicluster/istio-install.sh#L29) the deployment script tries to run `helm init`, however, there's no such command in Helm 3 that is by default installed to Cloud Shell machine, therefore the script freezes waiting for CRDs to be installed and that is not going to happen ever.

[Here's](https://gist.github.com/corebug/fa43fc91d8967a837cf1c3bdb1d563eb) the Cloud Chell console recap of trying to run this lab in QwikLabs.

**Comment by cgrant** [comment]
Closing as it was addressed in #65
